[pytest]

# Python path
pythonpath = .

# Test discovery
testpaths = tests

# Test file naming convention
python_files = test_*.py *_test.py

# Test class naming convention
python_classes = Test*

# Test function naming convention
python_functions = test_*

# Command-line options
addopts = -v

# Console output
log_cli = true
log_cli_level = INFO

# Testing log output
log_file = logs/pytest.log
log_file_level = INFO
